In [1]:
import numpy as np
import itertools

In [9]:
sentences = '''
sam is red
hannah not red
hannah is green
bob is green
bob not red
sam not green
sarah is red
sarah not green'''.strip() #.split('\n')
print(sentences)

sam is red
hannah not red
hannah is green
bob is green
bob not red
sam not green
sarah is red
sarah not green


In [2]:
sentences = '''
sam is red
hannah not red
hannah is green
bob is green
bob not red
sam not green
sarah is red
sarah not green'''.strip().split('\n')
is_green = np.asarray([[0, 1, 1, 1, 1, 0, 0, 0]], dtype='int32').T

print(sentences)
print(is_green)

['sam is red', 'hannah not red', 'hannah is green', 'bob is green', 'bob not red', 'sam not green', 'sarah is red', 'sarah not green']
[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]]


In [3]:
lemma = lambda x: x.strip().lower().split(' ')
sentences_lemmatized = [lemma(sentence) for sentence in sentences]
words = set(itertools.chain(*sentences_lemmatized))
print(words)

{'red', 'hannah', 'not', 'sam', 'bob', 'is', 'sarah', 'green'}


In [4]:
# diccionarios para convertir palabras a enteros y vice versa
word2idx = dict((v, i) for i, v in enumerate(words))
idx2word = list(words)

print(word2idx)
print(idx2word)

{'red': 0, 'hannah': 1, 'not': 2, 'sam': 3, 'bob': 4, 'is': 5, 'sarah': 6, 'green': 7}
['red', 'hannah', 'not', 'sam', 'bob', 'is', 'sarah', 'green']


In [5]:
# Convierte el enunciado en un arreglo numpy
to_idx = lambda x: [word2idx[word] for word in x]
sentences_idx = [to_idx(sentence) for sentence in sentences_lemmatized]
sentences_array = np.asarray(sentences_idx, dtype='int32')
print(sentences_idx)
print(sentences_array)

[[3, 5, 0], [1, 2, 0], [1, 5, 7], [4, 5, 7], [4, 2, 0], [3, 2, 7], [6, 5, 0], [6, 2, 7]]
[[3 5 0]
 [1 2 0]
 [1 5 7]
 [4 5 7]
 [4 2 0]
 [3 2 7]
 [6 5 0]
 [6 2 7]]
